import type { NextPage } from "next";
import Head from "next/head";

type Post = { title: string };
type HomeProps = { posts: Post[] };

const Home: NextPage<HomeProps> = ({ posts }) => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4">
        <div>{posts[0]?.title}</div>
      </main>
    </>
  );
};

// Get Posts data by reading metadata via gray-matter
export async function getStaticProps() {
  return { props: { posts: [{ title: "Initial" }] } };
}

export default Home;
