import type { NextPage } from "next";
import Head from "next/head";
import { MainLayout } from "../components/layouts/MainLayout";

type Post = { title: string };
type HomeProps = { posts: Post[] };

const Home: NextPage<HomeProps> = ({ posts }) => {
  return (
    <MainLayout>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>{posts[0]?.title}</div>
    </MainLayout>
  );
};

// Get Posts data by reading metadata via gray-matter
export async function getStaticProps() {
  // Iterate over files
  // Get File metadata
  // return it as static

  return { props: { posts: [{ title: "Initial" }] } };
}

export default Home;
